exports.PaperList=[
    {uniqueId:"CT-BS-1", name:"BITSAT-CT-CHEM-Bohr's Theory "},
 {uniqueId:"CT-BS-10", name:"BITSAT-CT-CHEM-Hybridization"},
 {uniqueId:"CT-BS-100", name:"BITSAT-CT-CHEM-Equivalent Concept "},
 {uniqueId:"CT-BS-101", name:"BITSAT-CT-CHEM-Simple Titration"},
 {uniqueId:"CT-BS-102", name:"BITSAT-CT-CHEM-Double & Back Titration"},
 {uniqueId:"CT-BS-103", name:"BITSAT-CT-CHEM-Gas Analysis & Hardenss of Water "},
 {uniqueId:"CT-BS-104", name:"BITSAT-CT-CHEM-Volume Strength of H2O2"},
 {uniqueId:"CT-BS-105", name:"BITSAT-CT-CHEM-Electronic Effects "},
 {uniqueId:"CT-BS-106", name:"BITSAT-CT-CHEM-Concepts of Acids and Bases "},
 {uniqueId:"CT-BS-107", name:"BITSAT-CT-CHEM-Reaction Intermediates "},
 {uniqueId:"CT-BS-108", name:"BITSAT-CT-CHEM-Preparation of Alkanes "},
 {uniqueId:"CT-BS-109", name:"BITSAT-CT-CHEM-Physical properties of alkanes "},
 {uniqueId:"CT-BS-11", name:"BITSAT-CT-CHEM-Hybridization-1"},
 {uniqueId:"CT-BS-110", name:"BITSAT-CT-CHEM-Miscellaneous reactions of alkanes "},
 {uniqueId:"CT-BS-111", name:"BITSAT-CT-CHEM-Preparation of Alkenes"},
 {uniqueId:"CT-BS-112", name:"BITSAT-CT-CHEM-Physical properties of alkenes"},
 {uniqueId:"CT-BS-113", name:"BITSAT-CT-CHEM-Electrophilic addition reaction of Alkenes "},
 {uniqueId:"CT-BS-114", name:"BITSAT-CT-CHEM-Preparation & properties of Na2CO3"},
 {uniqueId:"CT-BS-115", name:"BITSAT-CT-CHEM-Reaction of S-Block elements "},
 {uniqueId:"CT-BS-116", name:"BITSAT-CT-CHEM-Solubility, stability and flame tests of S-Block Elements "},
 {uniqueId:"CT-BS-117", name:"BITSAT-CT-CHEM-Reducing nature of S-Block Elements "},
 {uniqueId:"CT-BS-118", name:"BITSAT-CT-CHEM-Preparation & properties of NaHCO3, NaOH"},
 {uniqueId:"CT-BS-119", name:"BITSAT-CT-CHEM-Physical & chemical properties of S-Block Elements "},
 {uniqueId:"CT-BS-12", name:"BITSAT-CT-CHEM-Ionic and Covalent Bond-1"},
 {uniqueId:"CT-BS-120", name:"BITSAT-CT-CHEM-Preparation & properties of POP"},
 {uniqueId:"CT-BS-121", name:"BITSAT-CT-CHEM-Preparation & properties of Ca(OH)2, CaOCl2"},
 {uniqueId:"CT-BS-122", name:"BITSAT-CT-CHEM-Hydrogen peroxide "},
 {uniqueId:"CT-BS-123", name:"BITSAT-CT-CHEM-Position and preparation of Hydrogen "},
 {uniqueId:"CT-BS-124", name:"BITSAT-CT-CHEM-Diagonal relationship in S-Block Elements "},
 {uniqueId:"CT-BS-13", name:"BITSAT-CT-CHEM-Ionic Bond"},
 {uniqueId:"CT-BS-14", name:"BITSAT-CT-CHEM-Ionic and Covalent Bond-2"},
 {uniqueId:"CT-BS-15", name:"BITSAT-CT-CHEM-Ionic, Covalent and Co-ordinate Bond "},
 {uniqueId:"CT-BS-16", name:"BITSAT-CT-CHEM-Molecular Orbital Theory "},
 {uniqueId:"CT-BS-164", name:"BITSAT-CT-CHEM-Modern Periodic Table "},
 {uniqueId:"CT-BS-165", name:"BITSAT-CT-CHEM-Ionization Energy "},
 {uniqueId:"CT-BS-166", name:"BITSAT-CT-CHEM-Electron Affinity"},
 {uniqueId:"CT-BS-167", name:"BITSAT-CT-CHEM-Atomic Size"},
 {uniqueId:"CT-BS-168", name:"BITSAT-CT-CHEM-Electronegativity"},
 {uniqueId:"CT-BS-169", name:"BITSAT-CT-CHEM-Hydrides of Nitrogen"},
 {uniqueId:"CT-BS-17", name:"BITSAT-CT-CHEM-Hybridisation"},
 {uniqueId:"CT-BS-170", name:"BITSAT-CT-CHEM-Oxoacids of Phosphorous"},
 {uniqueId:"CT-BS-171", name:"BITSAT-CT-CHEM-Compounds of Nitrogen Family, Fertilizers"},
 {uniqueId:"CT-BS-172", name:"BITSAT-CT-CHEM-General Reactions of group 16"},
 {uniqueId:"CT-BS-173", name:"BITSAT-CT-CHEM-Oxoacids of Sulphur"},
 {uniqueId:"CT-BS-174", name:"BITSAT-CT-CHEM-Physical Properties of Group 16 Elements"},
 {uniqueId:"CT-BS-175", name:"BITSAT-CT-CHEM-Allotrops and Catanation of Sulphur"},
 {uniqueId:"CT-BS-176", name:"BITSAT-CT-CHEM-Compounds of Sulphur"},
 {uniqueId:"CT-BS-177", name:"BITSAT-CT-CHEM-Oxides of Sulphur"},
 {uniqueId:"CT-BS-178", name:"BITSAT-CT-CHEM-Other Compounds of Oxygen Family"},
 {uniqueId:"CT-BS-179", name:"BITSAT-CT-CHEM-Ideal and Non-Ideal Solutions"},
 {uniqueId:"CT-BS-18", name:"BITSAT-CT-CHEM-Valance Bond theory"},
 {uniqueId:"CT-BS-180", name:"BITSAT-CT-CHEM-Lowering of Vapour Pressure"},
 {uniqueId:"CT-BS-181", name:"BITSAT-CT-CHEM-Osmotic Pressure"},
 {uniqueId:"CT-BS-182", name:"BITSAT-CT-CHEM-Elevation in Boiling Point"},
 {uniqueId:"CT-BS-183", name:"BITSAT-CT-CHEM-Depression in Freezing Point"},
 {uniqueId:"CT-BS-184", name:"BITSAT-CT-CHEM-Henry's Law and Catalysis"},
 {uniqueId:"CT-BS-185", name:"BITSAT-CT-CHEM-Types of Ores"},
 {uniqueId:"CT-BS-186", name:"BITSAT-CT-CHEM-Concentration of Ores"},
 {uniqueId:"CT-BS-187", name:"BITSAT-CT-CHEM-Roasting and Calcination"},
 {uniqueId:"CT-BS-188", name:"BITSAT-CT-CHEM-Reduction of Metallic Ores"},
 {uniqueId:"CT-BS-189", name:"BITSAT-CT-CHEM-Refining of Metals"},
 {uniqueId:"CT-BS-19", name:"BITSAT-CT-CHEM-Critical Constants, Joule Thomson effect & Liquefaction of gases"},
 {uniqueId:"CT-BS-190", name:"BITSAT-CT-CHEM-Solubility Product"},
 {uniqueId:"CT-BS-191", name:"BITSAT-CT-CHEM-pH"},
 {uniqueId:"CT-BS-192", name:"BITSAT-CT-CHEM-Hydrolysis of Salts"},
 {uniqueId:"CT-BS-193", name:"BITSAT-CT-CHEM-Buffer Solutions"},
 {uniqueId:"CT-BS-194", name:"BITSAT-CT-CHEM-Theory of Indicators"},
 {uniqueId:"CT-BS-195", name:"BITSAT-CT-CHEM-Polyprotic Acids"},
 {uniqueId:"CT-BS-196", name:"BITSAT-CT-CHEM-Electrophilic Substitution Reaction"},
 {uniqueId:"CT-BS-197", name:"BITSAT-CT-CHEM-Aromaticity"},
 {uniqueId:"CT-BS-198", name:"BITSAT-CT-CHEM-Preparation of Benzene"},
 {uniqueId:"CT-BS-199", name:"BITSAT-CT-CHEM-Physical Properties of Benzene"},
 {uniqueId:"CT-BS-2", name:"BITSAT-CT-CHEM-Debroglie Duality"},
 {uniqueId:"CT-BS-20", name:"BITSAT-CT-CHEM-Ideal Gas Equation, Graham Law, Dalton Law of Partial Pressures "},
 {uniqueId:"CT-BS-200", name:"BITSAT-CT-CHEM-Vapour Pressurew"},
 {uniqueId:"CT-BS-201", name:"BITSAT-CT-CHEM-Bravais Lattice"},
 {uniqueId:"CT-BS-21", name:"BITSAT-CT-CHEM-Kinetic Theory of Gases"},
 {uniqueId:"CT-BS-22", name:"BITSAT-CT-CHEM-vander Waal's Equation, Deviation from Ideality"},
 {uniqueId:"CT-BS-23", name:"BITSAT-CT-CHEM-Bond Energy"},
 {uniqueId:"CT-BS-24", name:"BITSAT-CT-CHEM-Concept of Entropy"},
 {uniqueId:"CT-BS-25", name:"BITSAT-CT-CHEM-First Law of Thermodynamics"},
 {uniqueId:"CT-BS-26", name:"BITSAT-CT-CHEM-First Law of Thermodynamics-1"},
 {uniqueId:"CT-BS-27", name:"BITSAT-CT-CHEM-Hess Law"},
 {uniqueId:"CT-BS-28", name:"BITSAT-CT-CHEM-Pressure Volume Work"},
 {uniqueId:"CT-BS-29", name:"BITSAT-CT-CHEM-Equilibrium Constant, Lechatlier's Principle"},
 {uniqueId:"CT-BS-3", name:"BITSAT-CT-CHEM-Heisenberg Uncertainty Principle"},
 {uniqueId:"CT-BS-30", name:"BITSAT-CT-CHEM-Law of Mass Action, Equilibrium Constant, Lechatlier's Principle-1"},
 {uniqueId:"CT-BS-31", name:"BITSAT-CT-CHEM-Law of Mass Action, Equilibrium Constant, Lechatlier's Principle-2"},
 {uniqueId:"CT-BS-32", name:"BITSAT-CT-CHEM-Law of Mass Action, Equilibrium Constant, Lechatlier's Principle-3"},
 {uniqueId:"CT-BS-33", name:"BITSAT-CT-CHEM-First Order Reactions, Kinetics of Complex Reaction"},
 {uniqueId:"CT-BS-34", name:"BITSAT-CT-CHEM-Nuclear chemistry"},
 {uniqueId:"CT-BS-35", name:"BITSAT-CT-CHEM-Rate of Chemical Reaction-1"},
 {uniqueId:"CT-BS-36", name:"BITSAT-CT-CHEM-Rate of Chemical Reaction-2"},
 {uniqueId:"CT-BS-37", name:"BITSAT-CT-CHEM-Rate of Chemical Reaction-3"},
 {uniqueId:"CT-BS-38", name:"BITSAT-CT-CHEM-Rate of Chemical Reaction-4"},
 {uniqueId:"CT-BS-381", name:"BITSAT-CT-CHEM-Temperature Dependence of Rate"},
 {uniqueId:"CT-BS-382", name:"BITSAT-CT-CHEM-Second Order, Third Order Reaction"},
 {uniqueId:"CT-BS-383", name:"BITSAT-CT-CHEM-Kinetics of Complex Reactions"},
 {uniqueId:"CT-BS-384", name:"BITSAT-CT-CHEM-Zero Order Reactions"},
 {uniqueId:"CT-BS-385", name:"BITSAT-CT-CHEM-Chemical Properties of Alcohols, Ether & Phenols"},
 {uniqueId:"CT-BS-386", name:"BITSAT-CT-CHEM-Chemical Properties of Aldehydes and Ketones"},
 {uniqueId:"CT-BS-387", name:"BITSAT-CT-CHEM-Chemical Properties of Nitrogen Containing Compounds"},
 {uniqueId:"CT-BS-388", name:"BITSAT-CT-CHEM-Physical Properties of Alcohols, Ether & Phenols"},
 {uniqueId:"CT-BS-389", name:"BITSAT-CT-CHEM-Preparation of Nitrogen Containing Compounds"},
 {uniqueId:"CT-BS-39", name:"BITSAT-CT-CHEM-Concept of Acids and Bases"},
 {uniqueId:"CT-BS-390", name:"BITSAT-CT-CHEM-Preparation of Alcohols, Ether & Phenols"},
 {uniqueId:"CT-BS-391", name:"BITSAT-CT-CHEM-Preparation of Aldehydes & Ketones"},
 {uniqueId:"CT-BS-392", name:"BITSAT-CT-CHEM-Preparation of Carboxylic Acids & Their Derivatives"},
 {uniqueId:"CT-BS-393", name:"BITSAT-CT-CHEM-Hess Law"},
 {uniqueId:"CT-BS-394", name:"BITSAT-CT-CHEM-Extensive and Intensive Properties, State Variables, Path Function, Types of Process"},
 {uniqueId:"CT-BS-4", name:"BITSAT-CT-CHEM-Hydrogen Spectrum"},
 {uniqueId:"CT-BS-40", name:"BITSAT-CT-CHEM-Preparation of Alkenes"},
 {uniqueId:"CT-BS-41", name:"BITSAT-CT-CHEM-Miscellaneous Reactions of Alkynes"},
 {uniqueId:"CT-BS-42", name:"BITSAT-CT-CHEM-Reaction Intermediates "},
 {uniqueId:"CT-BS-43", name:"BITSAT-CT-CHEM-Nomenclature"},
 {uniqueId:"CT-BS-44", name:"BITSAT-CT-CHEM-Reaction Intermediates "},
 {uniqueId:"CT-BS-45", name:"BITSAT-CT-CHEM-Optical Isomerism"},
 {uniqueId:"CT-BS-46", name:"BITSAT-CT-CHEM-Tautomerism"},
 {uniqueId:"CT-BS-47", name:"BITSAT-CT-CHEM-Solubility and Stability of Salts"},
 {uniqueId:"CT-BS-48", name:"BITSAT-CT-CHEM-Water"},
 {uniqueId:"CT-BS-49", name:"BITSAT-CT-CHEM-Position of Hydrogen"},
 {uniqueId:"CT-BS-5", name:"BITSAT-CT-CHEM-Introduction of Schrodinger Wave Equation"},
 {uniqueId:"CT-BS-50", name:"BITSAT-CT-CHEM-Hydrogenperoxide"},
 {uniqueId:"CT-BS-51", name:"BITSAT-CT-CHEM-Solubility in Liquid Ammonia"},
 {uniqueId:"CT-BS-52", name:"BITSAT-CT-CHEM-Optical Isomerism"},
 {uniqueId:"CT-BS-53", name:"BITSAT-CT-CHEM-Conformational Isomerism"},
 {uniqueId:"CT-BS-54", name:"BITSAT-CT-CHEM-General Features-1"},
 {uniqueId:"CT-BS-55", name:"BITSAT-CT-CHEM-General Features-2"},
 {uniqueId:"CT-BS-56", name:"BITSAT-CT-CHEM-General Features-3"},
 {uniqueId:"CT-BS-57", name:"BITSAT-CT-CHEM-General Features-4"},
 {uniqueId:"CT-BS-58", name:"BITSAT-CT-CHEM-Faraday's Laws of Electrolysis"},
 {uniqueId:"CT-BS-59", name:"BITSAT-CT-CHEM-Electrochemical Cells"},
 {uniqueId:"CT-BS-6", name:"BITSAT-CT-CHEM-Planck's Quantum Theory"},
 {uniqueId:"CT-BS-60", name:"BITSAT-CT-CHEM-Electrolytic Conductance"},
 {uniqueId:"CT-BS-61", name:"BITSAT-CT-CHEM-Thermodynamics of Electrochemical Cell"},
 {uniqueId:"CT-BS-62", name:"BITSAT-CT-CHEM-Oxides of Halogens"},
 {uniqueId:"CT-BS-63", name:"BITSAT-CT-CHEM-Physical Properties of Group 13 Elements"},
 {uniqueId:"CT-BS-64", name:"BITSAT-CT-CHEM-Allotropes and Catenation of Carbon"},
 {uniqueId:"CT-BS-65", name:"BITSAT-CT-CHEM-Pollution and Environmental Chemistry-1"},
 {uniqueId:"CT-BS-66", name:"BITSAT-CT-CHEM-Pollution and Environmental Chemistry-2"},
 {uniqueId:"CT-BS-67", name:"BITSAT-CT-CHEM-Pollution and Environmental Chemistry-3"},
 {uniqueId:"CT-BS-68", name:"BITSAT-CT-CHEM-Pollution and Environmental Chemistry-4"},
 {uniqueId:"CT-BS-69", name:"BITSAT-CT-CHEM-Pollution and Environmental Chemistry-5"},
 {uniqueId:"CT-BS-7", name:"BITSAT-CT-CHEM-Quantum Numbers"},
 {uniqueId:"CT-BS-70", name:"BITSAT-CT-CHEM-Pollution and Environmental Chemistry-6"},
 {uniqueId:"CT-BS-71", name:"BITSAT-CT-CHEM-Pollution and Environmental Chemistry-7"},
 {uniqueId:"CT-BS-72", name:"BITSAT-CT-CHEM-Alcohol"},
 {uniqueId:"CT-BS-73", name:"BITSAT-CT-CHEM-Ethers"},
 {uniqueId:"CT-BS-74", name:"BITSAT-CT-CHEM-Phenols"},
 {uniqueId:"CT-BS-75", name:"BITSAT-CT-CHEM-Practical Organic Chemistry-1"},
 {uniqueId:"CT-BS-76", name:"BITSAT-CT-CHEM-Aldehydes And Ketones"},
 {uniqueId:"CT-BS-77", name:"BITSAT-CT-CHEM-Practical Organic Chemistry-2"},
 {uniqueId:"CT-BS-78", name:"BITSAT-CT-CHEM-Amines-1"},
 {uniqueId:"CT-BS-79", name:"BITSAT-CT-CHEM-Amines-2"},
 {uniqueId:"CT-BS-8", name:"BITSAT-CT-CHEM-Electronic Configuration"},
 {uniqueId:"CT-BS-80", name:"BITSAT-CT-CHEM-Amines-3"},
 {uniqueId:"CT-BS-81", name:"BITSAT-CT-CHEM-Principles Related to Experimental Chemistry-1"},
 {uniqueId:"CT-BS-82", name:"BITSAT-CT-CHEM-Principles Related to Experimental Chemistry-2"},
 {uniqueId:"CT-BS-83", name:"BITSAT-CT-CHEM-Extensive and intensive Properties"},
 {uniqueId:"CT-BS-84", name:"BITSAT-CT-CHEM-Classification and Analysis of Cations"},
 {uniqueId:"CT-BS-85", name:"BITSAT-CT-CHEM-Practical Organic Chemistry-3"},
 {uniqueId:"CT-BS-86", name:"BITSAT-CT-CHEM-Dalton's Law of Partial Pressure"},
 {uniqueId:"CT-BS-87", name:"BITSAT-CT-CHEM-Deviation from Ideality "},
 {uniqueId:"CT-BS-88", name:"BITSAT-CT-CHEM-Graham’s Law"},
 {uniqueId:"CT-BS-89", name:"BITSAT-CT-CHEM-Ideal Gas Equation"},
 {uniqueId:"CT-BS-9", name:"BITSAT-CT-CHEM-Dipole Moment"},
 {uniqueId:"CT-BS-90", name:"BITSAT-CT-CHEM-Jule Thomson effect & Liquefaction"},
 {uniqueId:"CT-BS-91", name:"BITSAT-CT-CHEM-vander Waal's Equation "},
 {uniqueId:"CT-BS-92", name:"BITSAT-CT-CHEM-Hydrogen Bonding"},
 {uniqueId:"CT-BS-93", name:"BITSAT-CT-CHEM-Metallic Bonding"},
 {uniqueId:"CT-BS-94", name:"BITSAT-CT-CHEM-Resonance"},
 {uniqueId:"CT-BS-95", name:"BITSAT-CT-CHEM-Aufbau principle"},
 {uniqueId:"CT-BS-96", name:"BITSAT-CT-CHEM-em Concept, Rutherford's Experiment"},
 {uniqueId:"CT-BS-97", name:"BITSAT-CT-CHEM-Hund's Rule"},
 {uniqueId:"CT-BS-98", name:"BITSAT-CT-CHEM-Pauli’s Exclusion Principle"},
 {uniqueId:"CT-BS-99", name:"BITSAT-CT-CHEM-Quantum Mechanical"},
 {uniqueId:"CT-BS-125", name:"BITSAT-CT-ENG-Antonyms "},
 {uniqueId:"CT-BS-126", name:"BITSAT-CT-ENG-Idioms & Phrases"},
 {uniqueId:"CT-BS-127", name:"BITSAT-CT-ENG-Jumbled Words"},
 {uniqueId:"CT-BS-128", name:"BITSAT-CT-ENG-One word for many"},
 {uniqueId:"CT-BS-129", name:"BITSAT-CT-ENG-One word substitution"},
 {uniqueId:"CT-BS-130", name:"BITSAT-CT-ENG-Reading Comprehension"},
 {uniqueId:"CT-BS-131", name:"BITSAT-CT-ENG-Sentence Completion-1"},
 {uniqueId:"CT-BS-132", name:"BITSAT-CT-ENG-Sentence Completion-2"},
 {uniqueId:"CT-BS-133", name:"BITSAT-CT-ENG-Sentence Improvement"},
 {uniqueId:"CT-BS-134", name:"BITSAT-CT-ENG-Sentence Reordering"},
 {uniqueId:"CT-BS-135", name:"BITSAT-CT-ENG-Spellings "},
 {uniqueId:"CT-BS-136", name:"BITSAT-CT-ENG-Synonyms "},
 {uniqueId:"CT-BS-202", name:"BITSAT-CT-LR-Letter Analogy"},
 {uniqueId:"CT-BS-203", name:"BITSAT-CT-LR-Number Analogy"},
 {uniqueId:"CT-BS-204", name:"BITSAT-CT-LR-Word Analogy"},
 {uniqueId:"CT-BS-205", name:"BITSAT-CT-LR-Chart Logic"},
 {uniqueId:"CT-BS-206", name:"BITSAT-CT-LR-Letter Classification"},
 {uniqueId:"CT-BS-207", name:"BITSAT-CT-LR-Number Classification"},
 {uniqueId:"CT-BS-208", name:"BITSAT-CT-LR-Word Classification"},
 {uniqueId:"CT-BS-209", name:"BITSAT-CT-LR-Figure Formation"},
 {uniqueId:"CT-BS-210", name:"BITSAT-CT-LR-Figure Matrix"},
 {uniqueId:"CT-BS-211", name:"BITSAT-CT-LR-Figure Series"},
 {uniqueId:"CT-BS-212", name:"BITSAT-CT-LR-Syllogism"},
 {uniqueId:"CT-BS-213", name:"BITSAT-CT-LR-Folding and Unfolding"},
 {uniqueId:"CT-BS-214", name:"BITSAT-CT-LR-Paper Cutting and Dot Situation"},
 {uniqueId:"CT-BS-215", name:"BITSAT-CT-LR-Figure Completion"},
 {uniqueId:"CT-BS-216", name:"BITSAT-CT-LR-Alphabet Series"},
 {uniqueId:"CT-BS-217", name:"BITSAT-CT-LR-Alphanumeric Series"},
 {uniqueId:"CT-BS-218", name:"BITSAT-CT-LR-Continuous Pattern Series"},
 {uniqueId:"CT-BS-219", name:"BITSAT-CT-LR-Number Series"},
 {uniqueId:"CT-BS-137", name:"BITSAT-CT-MATH-Conditional Identities, Inequalities and Graphs"},
 {uniqueId:"CT-BS-138", name:"BITSAT-CT-MATH-Compound, Multiple and Sub-multiple Angles"},
 {uniqueId:"CT-BS-139", name:"BITSAT-CT-MATH-Extreme Value of Trigonomtric Functions"},
 {uniqueId:"CT-BS-140", name:"BITSAT-CT-MATH-Concept of Homogenization"},
 {uniqueId:"CT-BS-141", name:"BITSAT-CT-MATH-Pair of Straight Lines"},
 {uniqueId:"CT-BS-142", name:"BITSAT-CT-MATH-Angle Bisectors of Pair of Straight Lines"},
 {uniqueId:"CT-BS-143", name:"BITSAT-CT-MATH-Parametric Form, Rotation & Translation of Axes"},
 {uniqueId:"CT-BS-144", name:"BITSAT-CT-MATH-Parabola, Ellipse, Hyperbola"},
 {uniqueId:"CT-BS-145", name:"BITSAT-CT-MATH-Problems on Locus"},
 {uniqueId:"CT-BS-146", name:"BITSAT-CT-MATH-Roots of Complex Equations"},
 {uniqueId:"CT-BS-147", name:"BITSAT-CT-MATH-Definition & Properties of Logarithms"},
 {uniqueId:"CT-BS-148", name:"BITSAT-CT-MATH-Logarithmic Inequalities and Graphs"},
 {uniqueId:"CT-BS-149", name:"BITSAT-CT-MATH-Problems Related to Series & Equation"},
 {uniqueId:"CT-BS-150", name:"BITSAT-CT-MATH-Remainder Theorem"},
 {uniqueId:"CT-BS-239", name:"BITSAT-CT-MATH-Angle between two curves"},
 {uniqueId:"CT-BS-240", name:"BITSAT-CT-MATH-Monotonocity and Maxima/Minima "},
 {uniqueId:"CT-BS-241", name:"BITSAT-CT-MATH-Differentiability Using First Principal"},
 {uniqueId:"CT-BS-242", name:"BITSAT-CT-MATH-Intermediate Value Theorem"},
 {uniqueId:"CT-BS-243", name:"BITSAT-CT-MATH-Investigating Function Using Functional Equation"},
 {uniqueId:"CT-BS-244", name:"BITSAT-CT-MATH-Types & Points of Discontinuity"},
 {uniqueId:"CT-BS-245", name:"BITSAT-CT-MATH-Integral of Inverse of a Function"},
 {uniqueId:"CT-BS-246", name:"BITSAT-CT-MATH-Integral of Periodic Function"},
 {uniqueId:"CT-BS-247", name:"BITSAT-CT-MATH-Limits as a Sum"},
 {uniqueId:"CT-BS-248", name:"BITSAT-CT-MATH-Newton-Leibnitz Rule"},
 {uniqueId:"CT-BS-249", name:"BITSAT-CT-MATH-Problem Based on Reduction Formula"},
 {uniqueId:"CT-BS-250", name:"BITSAT-CT-MATH-Problems Based on Partial Derivatives"},
 {uniqueId:"CT-BS-251", name:"BITSAT-CT-MATH-Derivate of Implicit Function"},
 {uniqueId:"CT-BS-252", name:"BITSAT-CT-MATH-Rules and Differentiation of Various Functions"},
 {uniqueId:"CT-BS-253", name:"BITSAT-CT-MATH-Higher Order Derivative"},
 {uniqueId:"CT-BS-254", name:"BITSAT-CT-MATH-Bijective and Inverse Function"},
 {uniqueId:"CT-BS-255", name:"BITSAT-CT-MATH-Composite Function"},
 {uniqueId:"CT-BS-256", name:"BITSAT-CT-MATH-Domain of a function"},
 {uniqueId:"CT-BS-257", name:"BITSAT-CT-MATH-Even and Odd Function"},
 {uniqueId:"CT-BS-258", name:"BITSAT-CT-MATH-Functional Equation"},
 {uniqueId:"CT-BS-259", name:"BITSAT-CT-MATH-Greatest Integer Function"},
 {uniqueId:"CT-BS-260", name:"BITSAT-CT-MATH-Modulus Function"},
 {uniqueId:"CT-BS-261", name:"BITSAT-CT-MATH-Concepts and Operations on Sets"},
 {uniqueId:"CT-BS-262", name:"BITSAT-CT-MATH-Graphical and Number of Solutions"},
 {uniqueId:"CT-BS-263", name:"BITSAT-CT-MATH-Periodic Function"},
 {uniqueId:"CT-BS-264", name:"BITSAT-CT-MATH-Range of a Function"},
 {uniqueId:"CT-BS-265", name:"BITSAT-CT-MATH-Relations and Types of Relations"},
 {uniqueId:"CT-BS-276", name:"BITSAT-CT-MATH-Binomial Series-I"},
 {uniqueId:"CT-BS-277", name:"BITSAT-CT-MATH-Definition & Coefficient of Any Term-I"},
 {uniqueId:"CT-BS-278", name:"BITSAT-CT-MATH-Definition & Coefficient of Any Term-II"},
 {uniqueId:"CT-BS-279", name:"BITSAT-CT-MATH-Problems Based on Definition and Concepts-I"},
 {uniqueId:"CT-BS-280", name:"BITSAT-CT-MATH-Problems Based on Definition and Concepts-II"},
 {uniqueId:"CT-BS-281", name:"BITSAT-CT-MATH-Modulus and Its Properties-I"},
 {uniqueId:"CT-BS-282", name:"BITSAT-CT-MATH-Modulus and Its Properties-II"},
 {uniqueId:"CT-BS-283", name:"BITSAT-CT-MATH-Concepts of Ellipse"},
 {uniqueId:"CT-BS-284", name:"BITSAT-CT-MATH-Geometrical Properties and Locus"},
 {uniqueId:"CT-BS-285", name:"BITSAT-CT-MATH-Chords, Tangent, Normal"},
 {uniqueId:"CT-BS-286", name:"BITSAT-CT-MATH-Condition of Tangency"},
 {uniqueId:"CT-BS-302", name:"BITSAT-CT-MATH-Rectangular Hyperbola and Its Properties"},
 {uniqueId:"CT-BS-303", name:"BITSAT-CT-MATH-Concepts of Hyperbola"},
 {uniqueId:"CT-BS-304", name:"BITSAT-CT-MATH-Chord, Tangent, Normal-I"},
 {uniqueId:"CT-BS-305", name:"BITSAT-CT-MATH-Chords, Tangents, Normal-II"},
 {uniqueId:"CT-BS-306", name:"BITSAT-CT-MATH-Equation of Tangents"},
 {uniqueId:"CT-BS-307", name:"BITSAT-CT-MATH-Definition and Properties of Logarithms"},
 {uniqueId:"CT-BS-308", name:"BITSAT-CT-MATH-Chords, Tangents, Normal"},
 {uniqueId:"CT-BS-309", name:"BITSAT-CT-MATH-Problems based on Algebraic Twin Form"},
 {uniqueId:"CT-BS-310", name:"BITSAT-CT-MATH-Linear and Quadratic Divided by Quadratic"},
 {uniqueId:"CT-BS-311", name:"BITSAT-CT-MATH-Application of Series to Find Limit"},
 {uniqueId:"CT-BS-312", name:"BITSAT-CT-MATH-Existence of Limits"},
 {uniqueId:"CT-BS-313", name:"BITSAT-CT-MATH-One Power Infinity "},
 {uniqueId:"CT-BS-314", name:"BITSAT-CT-MATH-Rationalization"},
 {uniqueId:"CT-BS-315", name:"BITSAT-CT-MATH-Direct Substitution of Limit"},
 {uniqueId:"CT-BS-316", name:"BITSAT-CT-MATH-Trigonometric Limits"},
 {uniqueId:"CT-BS-317", name:"BITSAT-CT-MATH-Linear Inequations"},
 {uniqueId:"CT-BS-318", name:"BITSAT-CT-MATH-Normal to a Parabola"},
 {uniqueId:"CT-BS-319", name:"BITSAT-CT-MATH-Concepts of Parabola"},
 {uniqueId:"CT-BS-320", name:"BITSAT-CT-MATH-Tangent to Parabola"},
 {uniqueId:"CT-BS-321", name:"BITSAT-CT-MATH-Properties in Parabola"},
 {uniqueId:"CT-BS-322", name:"BITSAT-CT-MATH-Circular Permutation"},
 {uniqueId:"CT-BS-323", name:"BITSAT-CT-MATH-Combination(with and without Repetition)"},
 {uniqueId:"CT-BS-324", name:"BITSAT-CT-MATH-Divison into Groups & Distribution"},
 {uniqueId:"CT-BS-325", name:"BITSAT-CT-MATH-Inclusion Exclusion Principle"},
 {uniqueId:"CT-BS-326", name:"BITSAT-CT-MATH-Multinomial Theorem"},
 {uniqueId:"CT-BS-327", name:"BITSAT-CT-MATH-Permutation(with and without Repetition)"},
 {uniqueId:"CT-BS-328", name:"BITSAT-CT-MATH-Roots of Quadratic Equation-I"},
 {uniqueId:"CT-BS-329", name:"BITSAT-CT-MATH-Roots of Quadratic Equation-II"},
 {uniqueId:"CT-BS-330", name:"BITSAT-CT-MATH-Roots of Quadratic Equation-III"},
 {uniqueId:"CT-BS-331", name:"BITSAT-CT-MATH-Roots of Quadratic Equation-IV"},
 {uniqueId:"CT-BS-332", name:"BITSAT-CT-MATH-Signs of Quadratic Expression "},
 {uniqueId:"CT-BS-333", name:"BITSAT-CT-MATH-Concepts of Straight Lines-I"},
 {uniqueId:"CT-BS-334", name:"BITSAT-CT-MATH-Concepts of Straight Lines-II"},
 {uniqueId:"CT-BS-335", name:"BITSAT-CT-MATH-Concepts of Straight Lines-III"},
 {uniqueId:"CT-BS-336", name:"BITSAT-CT-MATH-Slope and Equation of Line"},
 {uniqueId:"CT-BS-337", name:"BITSAT-CT-MATH-Angle Between Two Vectors, Projection Vector"},
 {uniqueId:"CT-BS-338", name:"BITSAT-CT-MATH-Linear Inequations"},
 {uniqueId:"CT-BS-339", name:"BITSAT-CT-MATH-Logarithmic and Exponential Series"},
 {uniqueId:"CT-BS-340", name:"BITSAT-CT-MATH-Inverse Trigonometric Functions"},
 {uniqueId:"CT-BS-350", name:"BITSAT-CT-MATH-Solution of Triangle-I"},
 {uniqueId:"CT-BS-351", name:"BITSAT-CT-MATH-Distance Between Different Centres"},
 {uniqueId:"CT-BS-352", name:"BITSAT-CT-MATH-Solution of Triangle-II"},
 {uniqueId:"CT-BS-353", name:"BITSAT-CT-MATH-Extreme Values of Trigonometric Functions"},
 {uniqueId:"CT-BS-358", name:"BITSAT-CT-MATH-Properties of Determinants-I"},
 {uniqueId:"CT-BS-359", name:"BITSAT-CT-MATH--Properties of Determinants-II"},
 {uniqueId:"CT-BS-369", name:"BITSAT-CT-MATH-Applications of Differential Eqns-II"},
 {uniqueId:"CT-BS-370", name:"BITSAT-CT-MATH-Applications of Differential Eqns-I"},
 {uniqueId:"CT-BS-371", name:"BITSAT-CT-MATH-Order, Degree and Formation of DE"},
 {uniqueId:"CT-BS-372", name:"BITSAT-CT-MATH-Solution of Differential Equation"},
 {uniqueId:"CT-BS-373", name:"BITSAT-CT-MATH-Solution of System of Linear Equations"},
 {uniqueId:"CT-BS-374", name:"BITSAT-CT-MATH-Transpose and Inverse of a Matrix"},
 {uniqueId:"CT-BS-375", name:"BITSAT-CT-MATH-Types and Operations on Matrices"},
 {uniqueId:"CT-BS-376", name:"BITSAT-CT-MATH-Problems Based on Conditional Probablity"},
 {uniqueId:"CT-BS-377", name:"BITSAT-CT-MATH-Law of Total Probability & Baye's Theorem"},
 {uniqueId:"CT-BS-378", name:"BITSAT-CT-MATH-Problems Based on Concepts of Probability-I"},
 {uniqueId:"CT-BS-379", name:"BITSAT-CT-MATH-Problems Based on Concepts of Probability-II"},
 {uniqueId:"CT-BS-380", name:"BITSAT-CT-MATH-Problems Based on Concepts of Probability-III"},
 {uniqueId:"CT-BS-395", name:"BITSAT-CT-MATH-Problem Based on Local/Global Maxima/Minima"},
 {uniqueId:"CT-BS-396", name:"BITSAT-CT-MATH-Problems Based on Mean Value Theorem"},
 {uniqueId:"CT-BS-397", name:"BITSAT-CT-MATH-3_Problems Based on Monotonocity"},
 {uniqueId:"CT-BS-398", name:"BITSAT-CT-MATH-Problems Based on Tangents"},
 {uniqueId:"CT-BS-399", name:"BITSAT-CT-MATH-Area Bounded by the Curves"},
 {uniqueId:"CT-BS-400", name:"BITSAT-CT-MATH-Inequalities, Definite Integration Using Graphs"},
 {uniqueId:"CT-BS-401", name:"BITSAT-CT-MATH-2_Problems Based on Properties"},
 {uniqueId:"CT-BS-402", name:"BITSAT-CT-MATH-Problems Based on By Parts"},
 {uniqueId:"CT-BS-403", name:"BITSAT-CT-MATH-Problems Based on Partial Fraction"},
 {uniqueId:"CT-BS-404", name:"BITSAT-CT-MATH-Problems Based on Substitution"},
 {uniqueId:"CT-BS-405", name:"BITSAT-CT-MATH-Continuity of Function"},
 {uniqueId:"CT-BS-406", name:"BITSAT-CT-MATH-Differentiability of Function"},
 {uniqueId:"CT-BS-407", name:"BITSAT-CT-MATH-Problems Based on Limits"},
 {uniqueId:"CT-BS-408", name:"BITSAT-CT-MATH-Types and Numbers of Functions"},
 {uniqueId:"CT-BS-409", name:"BITSAT-CT-MATH-Concepts of Sets-I"},
 {uniqueId:"CT-BS-410", name:"BITSAT-CT-MATH-Relation and Types of Relations"},
 {uniqueId:"CT-BS-411", name:"BITSAT-CT-MATH-Concepts of Sets-II"},
 {uniqueId:"CT-BS-412", name:"BITSAT-CT-MATH-Concepts of Sets-III"},
 {uniqueId:"CT-BS-429", name:"BITSAT-CT-MATH-Mean, Median and Mode"},
 {uniqueId:"CT-BS-430", name:"BITSAT-CT-MATH-Standard Deviation, Variance & Mean Deviation"},
 {uniqueId:"CT-BS-431", name:"BITSAT-CT-MATH-Problems Based on Optimization Under Constraints"},
 {uniqueId:"CT-BS-432", name:"BITSAT-CT-MATH-Mathematical Reasoning"},
 {uniqueId:"CT-BS-433", name:"BITSAT-CT-MATH-Cross Product of Vectors"},
 {uniqueId:"CT-BS-434", name:"BITSAT-CT-MATH-Concepts of 3D & Equations of Plane"},
 {uniqueId:"CT-BS-435", name:"BITSAT-CT-MATH-Geometrical Application of Vectors"},
 {uniqueId:"CT-BS-436", name:"BITSAT-CT-MATH-Concepts and Equations of Plane"},
 {uniqueId:"CT-BS-437", name:"BITSAT-CT-MATH-Problems Based on Concepts Vectors"},
 {uniqueId:"CT-BS-438", name:"BITSAT-CT-MATH-Product of Four Vectors"},
 {uniqueId:"CT-BS-439", name:"BITSAT-CT-MATH-Scalar Triple Product"},
 {uniqueId:"CT-BS-440", name:"BITSAT-CT-MATH-Equations of Straight Line and Plane"},
 {uniqueId:"CT-BS-441", name:"BITSAT-CT-MATH-Vector Triple Product"},
 {uniqueId:"CT-BS-459", name:"BITSAT-CT-MATH-Equation of Tangent in Various Form"},
 {uniqueId:"CT-BS-460", name:"BITSAT-CT-MATH-Family of Circles"},
 {uniqueId:"CT-BS-461", name:"BITSAT-CT-MATH-Radical Axis and Its Property"},
 {uniqueId:"CT-BS-462", name:"BITSAT-CT-MATH-Various Forms of Circles-I"},
 {uniqueId:"CT-BS-463", name:"BITSAT-CT-MATH-Various Forms of Circles-II"},
 {uniqueId:"CT-BS-464", name:"BITSAT-CT-MATH-Variable Seperable Method"},
 {uniqueId:"CT-BS-465", name:"BITSAT-CT-MATH-Summation, Differentiation, Integration"},
 {uniqueId:"CT-BS-466", name:"BITSAT-CT-MATH-Cramer's Rule"},
 {uniqueId:"CT-BS-467", name:"BITSAT-CT-MATH-Adjoint of a Matrix"},
 {uniqueId:"CT-BS-468", name:"BITSAT-CT-MATH-Problem Based on Mixed Events"},
 {uniqueId:"CT-BS-469", name:"BITSAT-CT-MATH-Problem Based on Independent Events"},
 {uniqueId:"CT-BS-470", name:"BITSAT-CT-MATH-Problems Based on Mutually Exclusive Events"},
 {uniqueId:"CT-BS-471", name:"BITSAT-CT-MATH-Problems Based on Compound Probability"},
 {uniqueId:"CT-BS-472", name:"BITSAT-CT-MATH-Problem Based on Repeated Trials"},
 {uniqueId:"CT-BS-473", name:"BITSAT-CT-MATH-AP and Its Mean"},
 {uniqueId:"CT-BS-474", name:"BITSAT-CT-MATH-HP and Its Mean, Inequalities of AM, GM, HM"},
 {uniqueId:"CT-BS-475", name:"BITSAT-CT-MATH-Problems Based on Special Series"},
 {uniqueId:"CT-BS-476", name:"BITSAT-CT-MATH-Trigonometric Inequalities"},
 {uniqueId:"CT-BS-477", name:"BITSAT-CT-MATH-Inequalities & Problems Based on Extreme Values"},
 {uniqueId:"CT-BS-478", name:"BITSAT-CT-MATH-Dot Product of Vectors"},
 {uniqueId:"CT-BS-479", name:"BITSAT-CT-MATH-Component of a Vector"},
 {uniqueId:"CT-BS-480", name:"BITSAT-CT-MATH-Linear Combination of Vectors"},
 {uniqueId:"CT-BS-481", name:"BITSAT-CT-MATH-Problems based on Collinearity "},
 {uniqueId:"CT-BS-482", name:"BITSAT-CT-MATH-Geometrical Application of Vectors-I"},
 {uniqueId:"CT-BS-483", name:"BITSAT-CT-MATH-Geometrical Application of Vectors-II"},
 {uniqueId:"CT-BS-484", name:"BITSAT-CT-MATH-Image in Line and Plane"},
 {uniqueId:"CT-BS-151", name:"BITSAT-CT-PHY-Impulse Momentum Theorem-2"},
 {uniqueId:"CT-BS-152", name:"BITSAT-CT-PHY-Head on Collision"},
 {uniqueId:"CT-BS-153", name:"BITSAT-CT-PHY-Oblique Collision"},
 {uniqueId:"CT-BS-154", name:"BITSAT-CT-PHY-Variable Mass System"},
 {uniqueId:"CT-BS-155", name:"BITSAT-CT-PHY-Floatation"},
 {uniqueId:"CT-BS-156", name:"BITSAT-CT-PHY-Barometer, Manometer, U-tube"},
 {uniqueId:"CT-BS-157", name:"BITSAT-CT-PHY-Time to Drain Out Liquid from a Container"},
 {uniqueId:"CT-BS-158", name:"BITSAT-CT-PHY-Siphonic action, Venturimeter, Pitot tube"},
 {uniqueId:"CT-BS-159", name:"BITSAT-CT-PHY-Pure Rotation Motion"},
 {uniqueId:"CT-BS-160", name:"BITSAT-CT-PHY-Hinge Reaction"},
 {uniqueId:"CT-BS-161", name:"BITSAT-CT-PHY-Energy in Combined Motion"},
 {uniqueId:"CT-BS-162", name:"BITSAT-CT-PHY-Velocity and Acceleration in Combined Motion"},
 {uniqueId:"CT-BS-163", name:"BITSAT-CT-PHY-Instantaneous Axis of Rotation"},
 {uniqueId:"CT-BS-220", name:"BITSAT-CT-PHY-Motional EMF"},
 {uniqueId:"CT-BS-221", name:"BITSAT-CT-PHY-Induced Currents and Motion of Conductors in Magnetic field"},
 {uniqueId:"CT-BS-222", name:"BITSAT-CT-PHY-Induced Electric Field"},
 {uniqueId:"CT-BS-223", name:"BITSAT-CT-PHY-Alternating Current and Its Properties"},
 {uniqueId:"CT-BS-224", name:"BITSAT-CT-PHY-LCR Based Circuits"},
 {uniqueId:"CT-BS-225", name:"BITSAT-CT-PHY-Power and Resonance in AC"},
 {uniqueId:"CT-BS-226", name:"BITSAT-CT-PHY-Parallel Circuits and Wheatstone Bridge"},
 {uniqueId:"CT-BS-227", name:"BITSAT-CT-PHY-Transformer and Choke Coil"},
 {uniqueId:"CT-BS-228", name:"BITSAT-CT-PHY-Torque on a charged particle in magnetic field"},
 {uniqueId:"CT-BS-229", name:"BITSAT-CT-PHY-Time Varying Magnetic Field"},
 {uniqueId:"CT-BS-230", name:"BITSAT-CT-PHY-LR Based Circuits"},
 {uniqueId:"CT-BS-231", name:"BITSAT-CT-PHY-Heat and Themodynamics"},
 {uniqueId:"CT-BS-232", name:"BITSAT-CT-PHY-Properties of Photon"},
 {uniqueId:"CT-BS-233", name:"BITSAT-CT-PHY-Dual Nature of Matter"},
 {uniqueId:"CT-BS-234", name:"BITSAT-CT-PHY-X rays and Mosley's Law"},
 {uniqueId:"CT-BS-235", name:"BITSAT-CT-PHY-Radioactivity, Parallel and Series Decay, Radioactive Equilibrium"},
 {uniqueId:"CT-BS-236", name:"BITSAT-CT-PHY-Error Analysis"},
 {uniqueId:"CT-BS-237", name:"BITSAT-CT-PHY-Velocity of Longitudinal and Transverse Waves"},
 {uniqueId:"CT-BS-238", name:"BITSAT-CT-PHY-Beats, Doppler effect;Transmission, Reflection and Energy Transfer in Waves"},
 {uniqueId:"CT-BS-266", name:"BITSAT-CT-PHY-Projectile Motion on horizontal plane"},
 {uniqueId:"CT-BS-267", name:"BITSAT-CT-PHY-Projectile motion on inclined plane"},
 {uniqueId:"CT-BS-268", name:"BITSAT-CT-PHY-Rain man problem"},
 {uniqueId:"CT-BS-269", name:"BITSAT-CT-PHY-Uniform and non-uniform circular motion"},
 {uniqueId:"CT-BS-270", name:"BITSAT-CT-PHY-Velocity of approach and separation"},
 {uniqueId:"CT-BS-271", name:"BITSAT-CT-PHY-Application of Newton's Second Law"},
 {uniqueId:"CT-BS-272", name:"BITSAT-CT-PHY-Bending of track"},
 {uniqueId:"CT-BS-273", name:"BITSAT-CT-PHY-Dynamics of circular motion"},
 {uniqueId:"CT-BS-274", name:"BITSAT-CT-PHY-Free Body diagram"},
 {uniqueId:"CT-BS-275", name:"BITSAT-CT-PHY-Multiple Block system"},
 {uniqueId:"CT-BS-287", name:"BITSAT-CT-PHY-Constraint equations"},
 {uniqueId:"CT-BS-288", name:"BITSAT-CT-PHY-Equilibrium of forces"},
 {uniqueId:"CT-BS-289", name:"BITSAT-CT-PHY-Static friction"},
 {uniqueId:"CT-BS-290", name:"BITSAT-CT-PHY-Angular momentum and Its Conservation"},
 {uniqueId:"CT-BS-291", name:"BITSAT-CT-PHY-Hinge reaction"},
 {uniqueId:"CT-BS-292", name:"BITSAT-CT-PHY-Moment of inertia of discrete and distributed mass"},
 {uniqueId:"CT-BS-293", name:"BITSAT-CT-PHY-Kinetic energy and Work-Energy Theorem in Rotational Motion - 1"},
 {uniqueId:"CT-BS-294", name:"BITSAT-CT-PHY-Kinetic energy and Work-Energy Theorem in Rotational Motion - 2"},
 {uniqueId:"CT-BS-295", name:"BITSAT-CT-PHY-torque "},
 {uniqueId:"CT-BS-296", name:"BITSAT-CT-PHY-Hinge Reaction"},
 {uniqueId:"CT-BS-297", name:"BITSAT-CT-PHY-Rolling Motion and Toppling"},
 {uniqueId:"CT-BS-298", name:"BITSAT-CT-PHY-Motion in Vertical Circle"},
 {uniqueId:"CT-BS-299", name:"BITSAT-CT-PHY-Power"},
 {uniqueId:"CT-BS-300", name:"BITSAT-CT-PHY-Work"},
 {uniqueId:"CT-BS-301", name:"BITSAT-CT-PHY-Work Energy Theorem for a Single Particle System"},
 {uniqueId:"CT-BS-341", name:"BITSAT-CT-PHY-Vectors & Parallelogram Law"},
 {uniqueId:"CT-BS-342", name:"BITSAT-CT-PHY-Dot and Cross Product"},
 {uniqueId:"CT-BS-343", name:"BITSAT-CT-PHY-Emission Spectrun in Bohr's Model"},
 {uniqueId:"CT-BS-344", name:"BITSAT-CT-PHY-Radioactivity, Parallel and Series Decay, Radioactive Equilibrium"},
 {uniqueId:"CT-BS-345", name:"BITSAT-CT-PHY-Nuclear Physics"},
 {uniqueId:"CT-BS-346", name:"BITSAT-CT-PHY-Properties of Photon"},
 {uniqueId:"CT-BS-347", name:"BITSAT-CT-PHY-Basics of Semiconductors"},
 {uniqueId:"CT-BS-348", name:"BITSAT-CT-PHY-Digital Electronics and Logic Gates"},
 {uniqueId:"CT-BS-349", name:"BITSAT-CT-PHY-Resolution of Vectors"},
 {uniqueId:"CT-BS-354", name:"BITSAT-CT-PHY-Centre of Mass"},
 {uniqueId:"CT-BS-355", name:"BITSAT-CT-PHY-Conservation of Mechanical Energy"},
 {uniqueId:"CT-BS-356", name:"BITSAT-CT-PHY-Head on Collision"},
 {uniqueId:"CT-BS-357", name:"BITSAT-CT-PHY-Impulse Momentum Theorem-1"},
 {uniqueId:"CT-BS-360", name:"BITSAT-CT-PHY-Pressure and Force Applied by fluid & Fluid Dynamics -1"},
 {uniqueId:"CT-BS-361", name:"BITSAT-CT-PHY-Pressure and Force Applied by fluid & Fluid Dynamics - 2"},
 {uniqueId:"CT-BS-362", name:"BITSAT-CT-PHY-Surface tension force, Capillary action & Excess pressure"},
 {uniqueId:"CT-BS-363", name:"BITSAT-CT-PHY-Viscosity and Stoke's Law"},
 {uniqueId:"CT-BS-364", name:"BITSAT-CT-PHY-1-D motion with constant acceleration"},
 {uniqueId:"CT-BS-365", name:"BITSAT-CT-PHY-1-D motion with variable acceleration "},
 {uniqueId:"CT-BS-366", name:"BITSAT-CT-PHY-Projectile Motion on horizontal plane"},
 {uniqueId:"CT-BS-367", name:"BITSAT-CT-PHY-Relative motion"},
 {uniqueId:"CT-BS-368", name:"BITSAT-CT-PHY-Uniform Circular Motion"},
 {uniqueId:"CT-BS-413", name:"BITSAT-CT-PHY-Drift velocity, Electric current in conductors and Current density"},
 {uniqueId:"CT-BS-414", name:"BITSAT-CT-PHY-Drift velocity, Ohm's Law, Resistance and its Properties"},
 {uniqueId:"CT-BS-415", name:"BITSAT-CT-PHY-Effective Resistance in network, Kirchoff's Law & Wheatstone bridge"},
 {uniqueId:"CT-BS-416", name:"BITSAT-CT-PHY-Current and Voltage Measuring Instruments"},
 {uniqueId:"CT-BS-417", name:"BITSAT-CT-PHY-R-C circuits & Heating effect of current"},
 {uniqueId:"CT-BS-418", name:"BITSAT-CT-PHY-Coulomb's Law & Properties of Charge "},
 {uniqueId:"CT-BS-419", name:"BITSAT-CT-PHY-Electrostatic field and potential energy, Equipotential surface & Properties of conductor"},
 {uniqueId:"CT-BS-420", name:"BITSAT-CT-PHY-Electrostatic field and potential & Properties of conductor"},
 {uniqueId:"CT-BS-421", name:"BITSAT-CT-PHY-Equipotential surfaces, Properties of conductor & Earthing"},
 {uniqueId:"CT-BS-422", name:"BITSAT-CT-PHY-Capacitors and Conductors"},
 {uniqueId:"CT-BS-423", name:"BITSAT-CT-PHY-Field and potential due to a dipole"},
 {uniqueId:"CT-BS-424", name:"BITSAT-CT-PHY-Biot-Savart law & its Applications"},
 {uniqueId:"CT-BS-425", name:"BITSAT-CT-PHY-Ampere's Circuital Law and Applications"},
 {uniqueId:"CT-BS-426", name:"BITSAT-CT-PHY-Motion of Charged Particles in Combined Field"},
 {uniqueId:"CT-BS-427", name:"BITSAT-CT-PHY-Magnetic Force on Current Carrying Wire"},
 {uniqueId:"CT-BS-428", name:"BITSAT-CT-PHY-Torque on a Current Carrying Loop"},
 {uniqueId:"CT-BS-442", name:"BITSAT-CT-PHY-Faraday's law & Lenz's Law"},
 {uniqueId:"CT-BS-443", name:"BITSAT-CT-PHY-Inductance- Self and Mutual"},
 {uniqueId:"CT-BS-444", name:"BITSAT-CT-PHY-Inductance- Self and Mutual & Inductor Based Circuit"},
 {uniqueId:"CT-BS-445", name:"BITSAT-CT-PHY-Inductor Based Circuit"},
 {uniqueId:"CT-BS-446", name:"BITSAT-CT-PHY-Motional emf, Induced electric field, Time varying magnetic field"},
 {uniqueId:"CT-BS-447", name:"BITSAT-CT-PHY-Magnetic flux, Faraday's law & Lenz's Law"},
 {uniqueId:"CT-BS-448", name:"BITSAT-CT-PHY-Induced Currents and Motion of Conductors in Magnetic field"},
 {uniqueId:"CT-BS-449", name:"BITSAT-CT-PHY-Dimensional analysis"},
 {uniqueId:"CT-BS-450", name:"BITSAT-CT-PHY-Error analysis"},
 {uniqueId:"CT-BS-451", name:"BITSAT-CT-PHY-Experiments"},
 {uniqueId:"CT-BS-452", name:"BITSAT-CT-PHY-Basic Properties of Reflection & Refraction"},
 {uniqueId:"CT-BS-453", name:"BITSAT-CT-PHY-Refraction through Plane and Spherical Surface and variable refractive index"},
 {uniqueId:"CT-BS-454", name:"BITSAT-CT-PHY-Refraction through Prism and Total Internal Reflection"},
 {uniqueId:"CT-BS-455", name:"BITSAT-CT-PHY-Deviation and Dispersion Through Prism"},
 {uniqueId:"CT-BS-456", name:"BITSAT-CT-PHY-Huygen Theory of Wave Fronts"},
 {uniqueId:"CT-BS-457", name:"BITSAT-CT-PHY-Refraction Through Spherical Surfaces, Lens Formula, Splitting and Silvering of lenses"},
 {uniqueId:"CT-BS-458", name:"BITSAT-CT-PHY-Spherical mirror and mirror formula; Relative motion of miror and object"},
 {uniqueId:"CT-BS-485", name:"BITSAT-CT-PHY-Escape speed and Binding energy"},
 {uniqueId:"CT-BS-486", name:"BITSAT-CT-PHY-gravitational force and field"},
 {uniqueId:"CT-BS-487", name:"BITSAT-CT-PHY-Graphs, Efficiency and Engines"},
 {uniqueId:"CT-BS-488", name:"BITSAT-CT-PHY-Modes of Heat Transfer"},
 {uniqueId:"CT-BS-489", name:"BITSAT-CT-PHY-Thermometry"},
 {uniqueId:"CT-BS-490", name:"BITSAT-CT-PHY-Equation of SHM; Relation between SHM and uniform circular motion"},
 {uniqueId:"CT-BS-491", name:"BITSAT-CT-PHY-Frequency and Amplitude of SHM, Systems performing SHM"},
 {uniqueId:"CT-BS-492", name:"BITSAT-CT-PHY-Simple and rigid pendulum"},
 {uniqueId:"CT-BS-493", name:"BITSAT-CT-PHY-Standing wave in organ pipe and in rod"},
 {uniqueId:"CT-BS-494", name:"BITSAT-CT-MATH-Solution of Simultaneous Trigonometric Equations"},
 {uniqueId:"CT-BS-495", name:"BITSAT-CT-PHY-Motion of planet and satellites in circular and elliptical path"},
 {uniqueId:"CT-BS-496", name:"BITSAT-CT-MATH-Co-normal Points"},
 {uniqueId:"CT-BS-497", name:"BITSAT-CT-MATH-Properties of Ellipse"},
 {uniqueId:"CT-BS-498", name:"BITSAT-CT-MATH-Co-normal Points & Properties of Hyperbola"},
 {uniqueId:"CT-BS-499", name:"BITSAT-CT-MATH-Fundamental Principles of Counting"},
 {uniqueId:"CT-BS-500", name:"BITSAT-CT-MATH-De-arrangement Principle"},
 {uniqueId:"CT-BS-501", name:"BITSAT-CT-MATH-Projection Formula & Napier's Analogy"},
 {uniqueId:"CT-BS-502", name:"BITSAT-CT-PHY-Velocity & acceleration of particles of medium during propogation"},
 {uniqueId:"CT-BS-503", name:"BITSAT-CT-MATH-m-n Theorem & Area of Triangle"},
 {uniqueId:"CT-BS-504", name:"BITSAT-CT-MATH-Solution of Simultaneous trigonometric equation-in one variable"}
];